### ISSUE TITLE
Update payment plans page

### ISSUE THREAD

**Issue by rubenkostucki** [makersacademy/site-mvp#200]
We're about to sign the agreement with Student Funder and Finance My Future.

Since we don't yet have our credit consumer licence (it'll take probably a few months, so let's not wait for it!), we cannot put the full breakdown of the loan on our payment page BUT we can link to Student Funder, Finance My Future and PCDL.

Here's how I would change/simplify the format of the payment page to:

Deposit: £800
Course cost: £8000
10% discount if paying 30 days before start date
£500 discount for females

Funding Options
Don't worry if you can't afford the upfront cost of the entire course. There are providers out there who's entire mission is helping you join Makers Academy and acquire invaluable skils

[Student Funder logo + link] [Finance My Future logo + link] [Skills Funding PCDL logo + link]

See a mockup attached

![img_6276](https://cloud.githubusercontent.com/assets/2648116/8377336/c5be16f2-1c10-11e5-9fdf-5ef3a51b4fb5.JPG)

**Comment by nikeshashar** [comment]
+1

**Comment by rubenkostucki** [comment]
@pitchinvasion see ref here for the wireframe I left on your desk. Happy to provide more info f2f

**Comment by sjmog** [comment]
Yes @rubenkostucki but my god THE ICONS

![](https://cdn.tutsplus.com/webdesign/uploads/2013/12/icons-windows.jpg)

Have a [little gander at this](http://webdesign.tutsplus.com/articles/use-and-abuse-of-icons-in-the-modern-age--webdesign-17064)

**Comment by rubenkostucki** [comment]
I know I know... well these are super ugly but it doesn't have to be and I
do think it appeals to the eye but whatever

On Thu, Jul 16, 2015 at 6:26 PM Sam Morgan <notifications@github.com> wrote:

> Yes @rubenkostucki <https://github.com/rubenkostucki> but my god THE ICONS
>
>
> <https://camo.githubusercontent.com/9b716090af8cf7be838b44880040897d05af587c/68747470733a2f2f63646e2e74757473706c75732e636f6d2f77656264657369676e2f75706c6f6164732f323031332f31322f69636f6e732d77696e646f77732e6a7067>
>
> Have a little gander at this
> <http://webdesign.tutsplus.com/articles/use-and-abuse-of-icons-in-the-modern-age--webdesign-17064>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/site-mvp/issues/200#issuecomment-122028341>
> .
>
-- 
*___________________________*

*Ruben Kostucki, **COO*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
<http://linkedin.com/in/rubenkostucki>

**Comment by pitchinvasion** [comment]
@samm seems fair enough although general assembly seem to do it quite well on their home page https://generalassemb.ly/

I'm happy to delegate to others on this but we'll obviously need some sort of design/mockup to build the ticket - would you or anyone else have time to put forward an alternative?

**Comment by nikeshashar** [comment]
I'd actually like to try something like this before discarding icons. Again, just because one or two articles don't like it, doesn't mean we have to follow those rules

**Comment by rubenkostucki** [comment]
The argument against icons: http://www.nngroup.com/articles/icon-usability/ and http://ux.stackexchange.com/questions/1795/when-to-use-icons-vs-icons-with-text-vs-just-text-links

The argument for: https://blog.kissmetrics.com/ui-ux-conversion-rates/

My take is this: icons ARE useful with text (which is part of my suggestion) and so long as they do communicate clearly what it is, eg http://img.talkandroid.com/uploads/2014/10/YogaStudio.png for yoga - quite clear, nope?

Can I suggest we actually do it and see how people feel about it? It seems that Nikesh and Leo agree with that + Leo heard from someone that the website was too content heavy. I would tend to agree with this and that the benefit section looks terrible

**Comment by rubenkostucki** [comment]
BTW I ll take care of finding the icons if that's what's needed :)

There are loads of free/paid ready made icons out there:

http://www.flaticon.com/free-icons/library_525
http://glyphicons.com/

**Comment by sjmog** [comment]
I don't want to be annoying here, but there's a lot of groundwork before we can include icons.

Icons are useful when one function (I.e. 'Go home') is repeated around the site. They are useful because the brain can recognise the image fractionally quicker than it can read the text. If an icon is used one-off, it provides zero cognitive benefit to the user, as it's just a picture.

Secondly, icons must be consistent in theme to not seem our-of-place. There are - quite literally - thousands of icon sets on the Internet. Currently, we use the icons from Linea. If we were going to use more icons they would have to be from there. This is mainly because the structure and weighting of icon lines and guides is identical throughout the icon set, and using more than one set of construction rules for icons will look weird.

Thirdly, I am really not pulling any of this out of my ass. Feel free to tweet or email prominent web designers to ask about icons. Read Apple's Human-Computer interaction guides, especially the sections on tab bars and icons. As I said before, icons have been debated for the past decade, so there is a lot of very well-supported research into their utility, placement, and effectiveness.

If this is better to do f2f, let's offline it.

**Comment by nikeshashar** [comment]
Yes - I would like to discuss this more. Because we are going back to being guided by others and not actually getting the product that the product owners want or need. 

I don't want to send potential clients to a page with reams of text about how to pay. No one reads the info - they just want to know how to pay and we have to make this as slick as possible.

**Comment by rubenkostucki** [comment]
From Finance My Future:

Please find our Logo in png and eps attached. In regard to the copy, please find below an example text that we use on various partner sites which has been approved by legal.

Future Finance Student Loans
We are really pleased to let you know that we have partnered with Future Finance (as an alternative source of funding for our students*).
The benefits of Future Finance are:

They offer loans to all students with a UK domiciled address, (assuming they meet appropriate credit checks, and are 18 or over) irrelevant to which level of study
Loans are offered from £2.5 -£40K, and can include living costs as well as tuition fees
Loans are repayable up to 10 years and three months after graduation
Students can apply for up to four payment breaks of 3 months each during the loan period
Representative 11.8% APR (variable).
* Further details of eligibility requirements, interest rates and other key terms of the loan are available by visiting the Future Finance website makers.financemyfuture.co.uk

Please note that other sources of funding may be available.

For examples you can visit:

https://www.cem.ac.uk/our-programmes/fees-funding/future-finance-student-loans.aspx
http://www.regents.ac.uk/study/scholarships-funding-and-bursaries/future-finance-loans.aspx
http://www.london.edu/education-and-development/masters-courses/getting-a-loan#.Va4L-flVhBc

**Comment by rubenkostucki** [comment]
Also, worth checking - https://thenounproject.com/

**Comment by sjmog** [comment]
Ruben is going to update this ticket with a more recent wireframe that I'll point up neatly - @rubenkostucki please can you upload the image of your latest?

**Comment by rubenkostucki** [comment]
content:

Learn cutting edge skills
Talks & Meetups
Team dedicated to Career Support
12 weeks FT, 4 weeks PT
A Macbook Pro Retina & 24'' Monitor
Coffee, Breakfast and Snacks
Yoga & Meditation Classes
Mentorship from Alumni & Large Community
Highly-selected peers to learn with

Course Cost
£8,000

Deposit: £800
Due to high demand for spaces, we ask that, once accepted, students pay an £800 deposit to lock-down their spot on the course.

Discount: 10%
We offer you a 10% discount if you pay the full tuition fees at least 1 month prior to the start of the pre-course

Female Scholarship: £500
We offer a £500 discount if you're female as we believe you are a highly underrepresented minority in the tech community.

Funding Options
Need funding assistance? We've got you covered! The following 3 organisations can provide you with loans to join our course

Disclaimer from the current website

Payment Options
We accept the following modes of payments

Cash 
Credit Cards
TransferWise
GoCardless
PayPal

**Comment by rubenkostucki** [comment]
![img_6490 jpg](https://cloud.githubusercontent.com/assets/2648116/8805704/9cd04134-2fca-11e5-9feb-9be06637fd6d.jpeg)
![finance-my-future-logo](https://cloud.githubusercontent.com/assets/2648116/8805929/de750c40-2fcb-11e5-8037-133c566c1f7a.png)
![studentfunder_logo](https://cloud.githubusercontent.com/assets/2648116/8805933/e269b8fa-2fcb-11e5-95e6-d00617d93f7f.png)
![skills-funding-agency-logo](https://cloud.githubusercontent.com/assets/2648116/8805931/e012c38a-2fcb-11e5-9ce7-eea619015a2b.png)

**Comment by rubenkostucki** [comment]
or another logo for Skills Funding Agency

![skills-funding-agency-logo](https://cloud.githubusercontent.com/assets/2648116/8806151/27c7a8b6-2fcd-11e5-9249-4af4233a4484.png)

**Comment by rubenkostucki** [comment]
@spike01 is this not in 'to do' for this sprint?

links for the Student Funder + PCDL + Finance My Future:

https://makers.financemyfuture.co.uk/
https://www.studentfunder.com/makersacademy/
https://www.gov.uk/career-development-loans/overview

**Comment by sjmog** [comment]
*yoink*
