### ISSUE TITLE
Make feedback tab pop

### ISSUE THREAD

**Issue by sjmog** [makersacademy/site-mvp#224]
The feedback tab needs to pop more.

Make it pop.

Roi, make it pop

pop
pop
pop
pop

**Comment by sjmog** [comment]
@roidriscoll

**Comment by sjmog** [comment]
@roidriscoll

**Comment by sjmog** [comment]
@roidriscoll

**Comment by sjmog** [comment]
@roidriscoll make it POP

**Comment by sjmog** [comment]
POP @roidriscoll

**Comment by roidriscoll** [comment]
Damn you to hell @sjmog
