### ISSUE TITLE
Keyword Update

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/site-mvp#228]
Keyword report from SEO site checker : 

Most common keywords : 

developer - 27 times
graduated - 26 times
junior - 25 times
manager - 8 times
programming - 7 times

One or more of our keywords are not in our meta title tags.

**Comment by nikeshashar** [comment]
![image](https://cloud.githubusercontent.com/assets/7963753/8482622/c8013aa8-20e2-11e5-8092-8902893ff3a2.png)

**Comment by pitchinvasion** [comment]
Nikesh Arfah wants to know what keywords you need so that Arfah can do this. Are they the largest words in that word cloud?

**Comment by nikeshashar** [comment]
At the moment yes - the largest words. But advice from SEO sites is to make sure that our content is paired / matched to any campaigns we run to multiply our organic growth online too

**Comment by Arfah** [comment]
I can't use the word developer in the meta as I'm using developers
