### ISSUE TITLE
Nav not hiding when you scroll down

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/site-mvp#240]
A bit of it pokes down as you scroll down

**Comment by pitchinvasion** [comment]
It also looks wrong when you squash it up

**Comment by sjmog** [comment]
Can you screenshot this? Struggling to reproduce

**Comment by roidriscoll** [comment]
<img width="1280" alt="screen shot 2015-07-09 at 14 36 21" src="https://cloud.githubusercontent.com/assets/2243253/8596537/e5b2a644-2647-11e5-896f-5a55529b03ab.png">

See at the top?

**Comment by sjmog** [comment]
Gotcha. I know what the issue is here - can I take this?

**Comment by pitchinvasion** [comment]
<img width="903" alt="screen shot 2015-07-09 at 14 37 19" src="https://cloud.githubusercontent.com/assets/208986/8596568/1138adea-2648-11e5-8f94-230b18894d6c.png">

Also this

**Comment by pitchinvasion** [comment]
Please do sam!

**Comment by pitchinvasion** [comment]
Oh also is there an easy way where if you move the mouse back up to the top it will show the nav again?

**Comment by pitchinvasion** [comment]
Maybe a different ticket, if so ignore

**Comment by sjmog** [comment]
Probably a different ticket - it'd have to be a Javascript listener on `mousemove` (think of a way to combine it with the `onScroll` event too)
