### ISSUE TITLE
Words wrap weirdly sometimes on mobile

### ISSUE THREAD

**Issue by sjmog** [makersacademy/site-mvp#253]
For super long headers, add this combo move to hyphenate/break words cross-browser:

```css
word-break: break-word;
-webkit-hyphens: auto;
-moz-hyphens: auto;
-ms-hyphens: auto;
hyphens: auto;
```

This will also stop the weird white gaps that are appearing to the side on some mobile pages.

**Comment by pitchinvasion** [comment]
should this be on all headers? And just at mobile breakpoints?

**Comment by sjmog** [comment]
I'm going to say YES and YES

**Comment by sjmog** [comment]
Also hopefully made less critical by #252
