### ISSUE TITLE
Fix hyphenation on mobile

### ISSUE THREAD

**Issue by spike01** [makersacademy/site-mvp#277]
Looks fine in Chrome, doesn't look fine on my iPhone 5:

![img_0765](https://cloud.githubusercontent.com/assets/7307631/8797819/dd09868c-2f95-11e5-9720-5e6d786ec47b.PNG)
![img_0766](https://cloud.githubusercontent.com/assets/7307631/8797818/dd09799e-2f95-11e5-8d28-3ce003c661e2.PNG)

**Comment by pitchinvasion** [comment]
samm sez: "try turning it off"

**Comment by sjmog** [comment]
That's cause hyphenation actually works in Safari.

Turn it off, enforce maximum lengths for words in headers?

Also more generally - these headers hauls never be more than 4 words. If more are needed, peeps should use a leader above the header to add stuff.
