### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/site-mvp#282]
Please remove this urgently : 

What is the average cohort size?
We have a hard limit of 30 students per cohort, but we we'd rather have smaller class sizes and focus on high-quality students over filling every class just to make a fast buck. These days the average class size is around 25 people.

**Comment by spike01** [comment]
Remove? Or just delete the last sentence?

**Comment by nikeshashar** [comment]
Remove the whole thing for now. I will re-write it later
