### ISSUE TITLE
Make website IE8 compatible or show a message

### ISSUE THREAD

**Issue by spike01** [makersacademy/site-mvp#292]
spike [3:30 PM] 
iexplore in all of its glorious forms only accounts for 5.57% of our traffic

spike [3:32 PM]
of which 25% of that traffic is from IE8 and below

spike [3:33 PM]
which is 1.39% of total site traffic. if we think it’s worth probably about a week of engineering work to support IE8, please let us know in the next sprint kick off.

evgeny [4:55 PM] 
@arfah: what’s the conversion rate of visits to applications?

ruben [4:56 PM] 
All should be on the metrics MD @evgeny

evgeny [5:00 PM] 
Thanks. So, it’s around 0.35. Then 3000 will translate into 10 applications, which will will translate into about 2 students, which will bring around 15-20k in revenue (fee + placement). Sounds like it’s worth a week’s of work?

**Comment by spike01** [comment]
spike [6:11 PM] 
converting to ie8 doesn’t sound like fun, @evgeny :simple_smile:
NEW MESSAGES

evgeny [6:11 PM] 
I know. Not insisting, would love to hear other opinions. What worried me not the initial effort but the ongoing overhead of checking that everything new that we do has ie8 support

evgeny [6:12 PM]
but it’s worth putting at least a banner for ie8 users saying “your browser sucks, use a better one”. There are loads of js plugins for that

**Comment by pitchinvasion** [comment]
I think the idea of just showing a banner is a very simple fix which would definitely help IE8 users. @arfah any ideas for some fun content, something like:

"Hey it looks like you're using a pretty old browser - here at Makers Academy we are always looking to use the most cutting-edge features the web offers and unfortunately your browser doesn't allow us to do this. We know you can't always switch, but we strongly recommend using [Google Chrome]() or [Mozilla Firefox]() instead
