### ISSUE TITLE
Build redesigned Curriculum Page

### ISSUE THREAD

**Issue by rubenkostucki** [makersacademy/site-mvp#301]
We've discussed the manifesto + Sam's article (https://docs.google.com/document/d/1tzrPcd1bgBPHVK-Enj5BMpwlf08UT9uFe0m3we2ITII/edit#heading=h.5dfykppw6g2d) as well as the letter I wrote a year ago that students receive.

Can we compile this into something nice for the Curriculum page? If there's an appeal for this, I don't mind making a wireframe with pen/paper

**Comment by nikeshashar** [comment]
@ruben we're going to have this on the blog - are you sure we want to duplicate content? Better of spending the extra effort in getting people to the page.

**Comment by rubenkostucki** [comment]
Maybe, but I think this is quite essential in making your mind to come to
Makers.

On the curriculum page we could have something like:

A Typical Day at Makers:

9.00-9.30 sit down, turn on your laptop, code kata
9.30-9.40 standup - what you did yesterday etc.
9.40-10.30 breakout
10.30-13.00 code
13.00-14.00 replenish your stomach
14.00-14.10 meditate for 10'
14.10-17.00 code
17.00-18.00 yoga twice a week
18.00-20.00 code
20.00-21.00 relax

With a 'read more' that links to Samm's blog post. (only issue is it seems
there's not that many hours of coding overall)

And we could have the 6 pillars of Makers with a read more to the manifesto

On Sun, Aug 2, 2015 at 12:16 PM Nikesh Ashar <notifications@github.com>
wrote:

> @ruben <https://github.com/ruben> we're going to have this on the blog -
> are you sure we want to duplicate content? Better of spending the extra
> effort in getting people to the page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/site-mvp/issues/301#issuecomment-127016385>
> .
>
-- 
*___________________________*

*Ruben Kostucki, **COO*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
<http://linkedin.com/in/rubenkostucki>

**Comment by sjmog** [comment]
Yep, I like Ruben's plan. Here's how I see the curriculum page breaking down:

```
MANIFESTO PILLARS INFOGRAPHIC
   <link to read more>
   ----------------   
    DAILY BREAKDOWN
   <link to read more>
   ----------------   
  WEEK-BY-WEEK TOPICS
    (in FAQ style)
   ----------------   
    APPLY SECTION
```

@rubenkostucki @nikeshashar

**Comment by nikeshashar** [comment]
@sjmog am I able to construct this like how arfah makes landing pages?

**Comment by rubenkostucki** [comment]
YES! That's exactly what I had in mind.

I spoke to the ex-CTO of UBS today who said: your site does NOT explain
what people are actually learning [beyond coding]. We need to make all the
soft skills / creativity / prototyping / team work / self-learning skills
much more prominent in my opinion, not removing the 'learn to code' of
course!

On Tue, Aug 4, 2015 at 12:21 PM Sam Morgan <notifications@github.com> wrote:

> Yep, I like Ruben's plan. Here's how I see the curriculum page breaking
> down:
>
> MANIFESTO PILLARS INFOGRAPHIC
>    <link to read more>
>    ----------------
>     DAILY BREAKDOWN
>    <link to read more>
>    ----------------
>   WEEK-BY-WEEK TOPICS
>     (in FAQ style)
>    ----------------
>     APPLY SECTION
>
> @rubenkostucki <https://github.com/rubenkostucki> @nikeshashar
> <https://github.com/nikeshashar>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/site-mvp/issues/301#issuecomment-127568835>
> .
>
-- 
*___________________________*

*Ruben Kostucki, **COO*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
<http://linkedin.com/in/rubenkostucki>

**Comment by sjmog** [comment]
- Manifesto pillars infographic could just be text, or an exciting depiction of it
- Daily breakdown could be a graph, for visual interest, possibly a vertical down-the-page one
- Week-by-week topics could be in FAQ style, with Roi's diagram alongside.

**Comment by sjmog** [comment]
Probably not @nikeshashar - there would be a few custom elements in here and this is a trickier page than static content (sorry). But I'll get on it today (probably this afternoon).

**Comment by nikeshashar** [comment]
At some point I'm going to have to see how to do this anyway @sjmog might be useful for me at some point to see how the site works.

**Comment by sjmog** [comment]
Sure thing dude - let's draft this up, and then I'll record myself doing the process :)
