### ISSUE TITLE
Facebook post lacks photo snapshots

### ISSUE THREAD

**Issue by rubenkostucki** [makersacademy/site-mvp#311]
If you post the website on Facebook, the images don't get loaded so it looks like this:

**Comment by rubenkostucki** [comment]
![screen shot 2015-08-04 at 15 10 12](https://cloud.githubusercontent.com/assets/2648116/9063263/8262f5d6-3abe-11e5-9c9c-ace6ff6927b0.png)

**Comment by nikeshashar** [comment]
The image has to be higher resolution : 

![image](https://cloud.githubusercontent.com/assets/7963753/9124017/6b56d0aa-3c8b-11e5-846a-ea6cc06ac166.png)

**Comment by rubenkostucki** [comment]
Also, why not photos of the office? There's normally a way to scroll lots
of photos... could be nicer, nope?

On Thu, Aug 6, 2015 at 10:35 PM Nikesh Ashar <notifications@github.com>
wrote:

> The image has to be higher resolution :
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/7963753/9124017/6b56d0aa-3c8b-11e5-846a-ea6cc06ac166.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/site-mvp/issues/311#issuecomment-128516754>
> .
>
-- 
*___________________________*

*Ruben Kostucki, **COO*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
<http://linkedin.com/in/rubenkostucki>

**Comment by nikeshashar** [comment]
Baby steps. 

Excuse typos - make errors my fingers 
 

On 7 Aug 2015, at 09:58, Ruben Kostucki <notifications@github.com> wrote:

Also, why not photos of the office? There's normally a way to scroll lots
of photos... could be nicer, nope?

On Thu, Aug 6, 2015 at 10:35 PM Nikesh Ashar <notifications@github.com>
wrote:

> The image has to be higher resolution :
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/7963753/9124017/6b56d0aa-3c8b-11e5-846a-ea6cc06ac166.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/site-mvp/issues/311#issuecomment-128516754>
> .
>
-- 
*___________________________*

*Ruben Kostucki, **COO*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki> | Linkedin
<http://linkedin.com/in/rubenkostucki>
