### ISSUE TITLE
Curriculum page content

### ISSUE THREAD

**Issue by rubenkostucki** [makersacademy/site-mvp#335]
LEARNING IS SO MUCH MORE THAN A CURRICULUM AND SOME EDUCATIONAL MATERIALS. We currently use a mixture of workshops, exercises, projects, classroom break-out sessions and end-of-week challenges to help our students understand programming.

is the same content as

We believe that learning to code consists of much more than just the materials we provide and the curriculum we have created. We currently use a mixture of workshops, exercises, projects, classroom break-out sessions and end-of-week challenges to help our students understand programming.

---

We should probably remove the second paragraph on that page or change the content totally. Duplicating content is not good for SEO nor it is visually not useful :)

**Comment by nikeshashar** [comment]
@rubenkostucki - is this comment based on the new curriculum page?

**Comment by rubenkostucki** [comment]
Yes Nikesh!

[image: Screen Shot 2015-08-13 at 09.35.27.png]
See screenshot attached.

On Thu, Aug 13, 2015 at 12:25 AM Nikesh Ashar <notifications@github.com>
wrote:

> @rubenkostucki <https://github.com/rubenkostucki> - is this comment based
> on the new curriculum page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/site-mvp/issues/335#issuecomment-130475848>
> .
>
-- 
*___________________________*

*Ruben Kostucki, **COO*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
<http://linkedin.com/in/rubenkostucki>

**Comment by rubenkostucki** [comment]
![screen shot 2015-08-13 at 09 35 27](https://cloud.githubusercontent.com/assets/2648116/9245783/ca1d086c-419e-11e5-9c8a-381dbf26d7d3.png)

**Comment by nikeshashar** [comment]
@rubenkostucki - do you have alternative content ? I can make the change tomorrow.

**Comment by rubenkostucki** [comment]
Not right now. Arfah/Ollie should probably take care of this Nikesh. This
ties in with the feedback my cousin made
https://waffle.io/makersacademy/engineering/cards/55c34dc38db8150f008003b4

I think content should be reviewed since the launch + watching some hotjar
recordings etc.

On Sun, Aug 16, 2015 at 7:55 PM Nikesh Ashar <notifications@github.com>
wrote:

> @rubenkostucki <https://github.com/rubenkostucki> - do you have
> alternative content ? I can make the change tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/site-mvp/issues/335#issuecomment-131601610>
> .
>
-- 
*___________________________*

*Ruben Kostucki, **COO*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
<http://linkedin.com/in/rubenkostucki>
