### ISSUE TITLE
my face is squashed on the blog

### ISSUE THREAD

**Issue by rubenkostucki** [makersacademy/site-mvp#340]
http://blog.makersacademy.com/our-education-manifesto/

**Comment by spike01** [comment]
That's a problem with your picture. Use a smaller picture!

**Comment by rubenkostucki** [comment]
cool. will change it

On Tue, Aug 11, 2015 at 5:15 PM Spike <notifications@github.com> wrote:

> That's a problem with your picture. Use a smaller picture!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/site-mvp/issues/340#issuecomment-129952144>
> .
>
-- 
*___________________________*

*Ruben Kostucki, **COO*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
<http://linkedin.com/in/rubenkostucki>
