### ISSUE TITLE
SEO review for new site

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/site-mvp#65]
As a marketer 
So that the site shows up in google
I want to review that the site is SEO compliant

**Comment by nikeshashar** [comment]
Results from SEO Checker : 

- [ ] 16 images tags are missing ALT attributes
- [ ] 51 inline CSS styles
- [ ] Add a print style sheet
- [ ] Need robots.txt file
- [ ] Need a sitemap
- [ ] CSS Sprites to lower HTTP requests
- [ ] Image map for Curriculum
- [ ] Minify Hotjar JS file
- [ ] Add CName for IP to Domain (IP Canonicalization for 199.27.76.133 )
- [ ] No social media activity.
- [ ] Social media META tags

Current score 75 / 100 on 02 July 2015 (seositecheckup.com). More tests to follow

**Comment by pitchinvasion** [comment]
https://github.com/statonjr/middleman-sitemap

**Comment by stephenlloyd** [comment]
@nikeshashar can you send me the link to the checker you used please?

**Comment by nikeshashar** [comment]
http://seositecheckup.com/

That's the first pass and then I will use more.
